FROM node:20-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
RUN npm run prisma:generate && npm run build
CMD ["sh", "-c", "npm run prisma:migrate && npm run start"]
